spring:
  datasource:
    url: jdbc:mysql://localhost:3306/node
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    properties:
       hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
